default_language_version:
    python: python3.10
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.1.0
        hooks:
        -   id: debug-statements
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v3.0.1
        hooks:
        -   id: reorder-python-imports
    -   repo: https://github.com/ambv/black
        rev: 22.1.0
        hooks:
        -   id: black
